### PR TITLE
Add php-7.1

### PR DESCRIPTION
**Pull request by adam-paterson**

### CODE REVIEW

**Comment by punkstar** [comment]
Sorry mate, there was a big old PR over at #48 that changed the way we do templating now.

**Review by punkstar — CHANGES_REQUESTED** [review]
Change to use JSON configuration instead of makefile.

**Comment by adam-paterson** [comment]
No problem!

**Comment by punkstar** [comment]
Can you lob 7.1 in the travis.yml please so we can get this tested?

**Comment by punkstar** [comment]
Looks like there's a problem with ioncube and 7.1.

**Comment by adam-paterson** [comment]
@punkstar Yeah, it looks like Ioncube loader doesn't support 7.1 yet. What do you suggest here?

**Comment by punkstar** [comment]
@adam-paterson Removing it and adding a ticket so we can add it back in when 7.1 support is released.

**Comment by punkstar** [comment]
Thanks!

**Pull request merged**
